// List of job titles
export const jobTitles = [
    "AI Architect",
    "AI Data Scientist",
    "AI Developer",
    "AI Engineer",
    "AI Product Manager",
    "AI Programmer",
    "AI Research Engineer",
    "AI Research Scientist",
    "AI Researcher",
    "AI Scientist",
    "AI Software Development Engineer",
    "AI Software Engineer",
    "AI Solution Architect",
    "AI Specialist",
    "AWS Data Architect",
    "Admin & Data Analyst",
    "Analytics Engineer",
    "Analytics Engineering Manager",
    "Applied Data Scientist",
    "Applied Machine Learning Engineer",
    "Applied Machine Learning Scientist",
    "Applied Research Scientist",
    "Applied Scientist",
    "Artificial Intelligence Engineer",
    "Associate",
    "Autonomous Vehicle Technician",
    "Azure Data Engineer",
    "BI Analyst",
    "BI Data Analyst",
    "BI Data Engineer",
    "BI Developer",
    "BI Engineer",
    "Backend Engineer",
    "Bear Robotics",
    "Big Data Architect",
    "Big Data Developer",
    "Big Data Engineer",
    "Business Analyst",
    "Business Data Analyst",
    "Business Intelligence",
    "Business Intelligence Analyst",
    "Business Intelligence Consultant",
    "Business Intelligence Data Analyst",
    "Business Intelligence Developer",
    "Business Intelligence Engineer",
    "Business Intelligence Lead",
    "Business Intelligence Manager",
    "Business Intelligence Specialist",
    "CRM Data Analyst",
    "Cloud Data Architect",
    "Cloud Data Engineer",
    "Cloud Database Administrator",
    "Cloud Database Engineer",
    "Compliance Data Analyst",
    "Computational Biologist",
    "Computer Vision Engineer",
    "Computer Vision Software Engineer",
    "Consultant Data Engineer",
    "Data Analyst",
    "Data Analyst Lead",
    "Data Analytics Associate",
    "Data Analytics Consultant",
    "Data Analytics Engineer",
    "Data Analytics Lead",
    "Data Analytics Manager",
    "Data Analytics Specialist",
    "Data Analytics Team Lead",
    "Data Architect",
    "Data DevOps Engineer",
    "Data Developer",
    "Data Engineer",
    "Data Governance Analyst",
    "Data Governance Engineer",
    "Data Governance Lead",
    "Data Governance Manager",
    "Data Governance Specialist",
    "Data Infrastructure Engineer",
    "Data Integration Analyst",
    "Data Integration Coordinator",
    "Data Integration Developer",
    "Data Integration Engineer",
    "Data Integration Specialist",
    "Data Lead",
    "Data Management Analyst",
    "Data Management Associate",
    "Data Management Consultant",
    "Data Management Lead",
    "Data Management Manager",
    "Data Management Specialist",
    "Data Manager",
    "Data Modeler",
    "Data Operations Analyst",
    "Data Operations Associate",
    "Data Operations Engineer",
    "Data Operations Manager",
    "Data Operations Specialist",
    "Data Pipeline Engineer",
    "Data Product Manager",
    "Data Product Owner",
    "Data Quality Analyst",
    "Data Quality Engineer",
    "Data Quality Manager",
    "Data Quality Specialist",
    "Data Reporting Analyst",
    "Data Science Tech Lead",
    "Data Scientist",
    "Data Scientist Lead",
    "Data Specialist",
    "Data Strategist",
    "Data Strategy Lead",
    "Data Strategy Manager",
    "Data Team Lead",
    "Data Visualization Analyst",
    "Data Visualization Developer",
    "Data Visualization Engineer",
    "Data Visualization Specialist",
    "DataOps Engineer",
    "Decision Scientist",
    "Deep Learning Engineer",
    "Deep Learning Researcher",
    "DevOps Engineer",
    "Director of Business Intelligence",
    "ETL Developer",
    "ETL Engineer",
    "Encounter Data Management Professional",
    "Engineering Manager",
    "Finance Data Analyst",
    "Financial Data Analyst",
    "Frontend Engineer",
    "Full Stack Engineer",
    "Head of AI",
    "Head of Business Intelligence",
    "Head of Data",
    "Head of Machine Learning",
    "Insight Analyst",
    "Lead AI Engineer",
    "Lead Data Analyst",
    "Lead Data Engineer",
    "Lead Data Scientist",
    "Lead Machine Learning Engineer",
    "ML Infrastructure Engineer",
    "MLOps Engineer",
    "Machine Learning Architect",
    "Machine Learning Developer",
    "Machine Learning Engineer",
    "Machine Learning Infrastructure Engineer",
    "Machine Learning Manager",
    "Machine Learning Model Engineer",
    "Machine Learning Modeler",
    "Machine Learning Platform Engineer",
    "Machine Learning Quality Engineer",
    "Machine Learning Research Engineer",
    "Machine Learning Researcher",
    "Machine Learning Scientist",
    "Machine Learning Software Engineer",
    "Machine Learning Specialist",
    "Manager Data Management",
    "Marketing Data Analyst",
    "Marketing Data Engineer",
    "Marketing Data Scientist",
    "Master Data Specialist",
    "NLP Engineer",
    "Platform Engineer",
    "Power BI Developer",
    "Principal Data Analyst",
    "Principal Data Architect",
    "Principal Data Engineer",
    "Principal Data Scientist",
    "Principal Machine Learning Engineer",
    "Principal Statistical Programmer",
    "Product Data Analyst",
    "Prompt Engineer",
    "Python Developer",
    "Quantitative Research Analyst",
    "Quantitative Researcher",
    "Research Analyst",
    "Research Associate",
    "Research Engineer",
    "Research Scientist",
    "Robotics Engineer",
    "Robotics Software Engineer",
    "SAS Developer",
    "Sales Data Analyst",
    "Site Reliability Engineer",
    "Software Data Engineer",
    "Software Developer",
    "Software Development Engineer",
    "Software Engineer",
    "Solutions Architect",
    "Solutions Engineer",
    "Staff Data Analyst",
    "Staff Data Scientist",
    "Staff Machine Learning Engineer",
    "Statistical Programmer",
    "Systems Engineer",
    "Technical Lead"
  ];
  
  // List of residencies
  export const residencies = [
    "AD", "AE", "AM", "AR", "AS", "AT", "AU", "BA", "BE", "BG", "BM", "BO", "BR", "CA", "CF", 
    "CH", "CL", "CN", "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "DZ", "EC", "EE", "EG", "ES", 
    "FI", "FR", "GB", "GE", "GH", "GR", "HK", "HN", "HR", "HU", "ID", "IE", "IL", "IN", "IQ", 
    "IR", "IT", "JE", "JP", "KE", "KR", "KW", "LB", "LT", "LU", "LV", "MD", "MT", "MU", "MX", 
    "MY", "NG", "NL", "NO", "NZ", "OM", "PE", "PH", "PK", "PL", "PR", "PT", "QA", "RO", "RS", 
    "RU", "SA", "SE", "SG", "SI", "SK", "TH", "TN", "TR", "UA", "UG", "US", "UZ", "VE", "VN", "ZA"
  ];
  